spring.application.name=diary


#DB 세팅
spring.datasource.url=jdbc:mysql://localhost:3306/diary_db
spring.datasource.username=springuser
spring.datasource.password=spring1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 